name: Generate macOS Tahoe ISO

on:
  workflow_dispatch:

run-name: Generate macOS Tahoe 26.6.1 ISO

env:
  installer_version: "26.6.1"
  installer_name: "Tahoe"

jobs:
  build:
    runs-on: macos-15-intel

    steps:
      - name: Download macOS Installer
        run: |
          softwareupdate --list-full-installers
          softwareupdate --fetch-full-installer --full-installer-version ${{ env.installer_version }}

      - name: Generate macOS ISO Installer
        run: |
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 22000m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction
          hdiutil eject -force /Volumes/'${{ env.installer_name }}'
          hdiutil convert /tmp/'${{ env.installer_name }}'.dmg -format UDTO -o ~/Desktop/'${{ env.installer_name }}'
          mv ~/Desktop/'${{ env.installer_name }}'.cdr ~/Desktop/'${{ env.installer_name }}'.iso
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg

      - name: Upload ISO
        uses: actions/upload-artifact@v7
        with:
          name: macOS-Tahoe-26.6.1-ISO
          path: "~/Desktop/${{ env.installer_name }}.iso"
