name: Generate macOS Tahoe ISO

on:
  workflow_dispatch: # 保留手动触发

run-name: Generate macOS Tahoe v26.6.1 ISO

env:
  installer_version: "26.6.1"
  installer_name: "Tahoe"

jobs:
  build:
    # 建议使用具体的 macOS 版本，macOS 26 对应 macos-26 镜像
    runs-on: macos-latest
    steps:
      # Download Installer
      - name: Download macOS Installer
        run: |
          sudo /System/Library/PrivateFrameworks/Seeding.framework/Versions/A/Resources/seedutil enroll PublicSeed
          softwareupdate --list-full-installers
          softwareupdate --fetch-full-installer --full-installer-version ${{ env.installer_version }}

      # Generate ISO Installer
      - name: Generate macOS ISO Installer
        run: |
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 16800m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction
          echo "Sleeping 100 to allow the installer to finish"
          sleep 100
          hdiutil eject -force /Volumes/'Install macOS ${{ env.installer_name }}'
          hdiutil convert /tmp/'${{ env.installer_name }}'.dmg -format UDTO -o ~/Desktop/'${{ env.installer_name }}'
          mv -v ~/Desktop/'${{ env.installer_name }}'.cdr ~/Desktop/'${{ env.installer_name }}'.iso
          sudo rm -fv /tmp/'${{ env.installer_name }}'.dmg

      # Upload ISO
      - name: Upload ISO
        uses: actions/upload-artifact@v7
        with:
          name: macOS ${{ env.installer_name }} ${{ env.installer_version }} ISO
          path: ~/Desktop/${{ env.installer_name }}.iso
